#!/bin/bash
printf "You have reset your pasword. Your temporary password for login is: $1\nYou can change it after logging in with the CoEngage App" |  mail -s "CoEngage registration" $2
echo Email sent to $2
